#!/bin/bash

echo "Cleaning install dir and remake it"

rm -rf ~/iot-install
mkdir ~/iot-install
cd ~/iot-install

echo "Cloning repos"

git clone https://github.com/rfaita/iot-tsa.git
git clone https://github.com/rfaita/iot-tsp.git
git clone https://github.com/rfaita/iot-edge.git
git clone https://github.com/rfaita/iot-infra.git


echo "Replaces"

find . -iname *yml | xargs sed -i "s/<CHANGEIT_USER>/$1/g"
find . -iname *yml | xargs sed -i "s/<CHANGEIT_PASS>/$2/g"

echo "Compile Repos"

cd iot-tsa && mvn clean install
cd ../iot-tsp && mvn clean install
cd ../iot-edge && mvn clean install

cd ../iot-infra

echo "Build Images"

docker-compose build

echo "Start Images"

docker-compose up -d