#!/bin/bash

echo "Cleaning install dir and remake it"

rm -rf ~/iot-install
mkdir ~/iot-install
cd ~/iot-install

echo "Cloning repos"

git clone https://github.com/rfaita/iot-tsa.git
git clone https://github.com/rfaita/iot-tsp.git
git clone https://github.com/rfaita/iot-edge.git
git clone https://github.com/rfaita/iot-infra.git


echo "Replaces"

sed -i 's/<CHANGEIT_USER>/$1/g' iot-intra/docker-compose.yml
sed -i 's/<CHANGEIT_PASS>/$2/g' iot-intra/docker-compose.yml


sed -i 's/<CHANGEIT_USER>/$1/g' iot-edge/src/main/resources/application.yml
sed -i 's/<CHANGEIT_PASS>/$2/g' iot-edge/src/main/resources/application.yml

echo "Compile Repos"

cd iot-tsa && mvn clean install
cd ../iot-tsp && mvn clean install
cd ../iot-edge && mvn clean install

cd ../iot-infra

echo "Build Images"

docker-compose build

echo "Start Images"

docker-compose up -d